version: "3" # 根据你的docker-compose进行修改
services:
  danmuji:
    # 阿里镜像地址
    # image: registry.cn-hangzhou.aliyuncs.com/zzcabc/danmuji:latest
    # dockerhub镜像地址
    image: zzcabc/danmuji
    # 容器名称
    container_name: danmuji
    # 启动方式 always 在容器退出时总是重启容器
    # unless-stopped，在容器退出时总是重启容器，但是不考虑在Docker守护进程启动时就已经停止了的容器
    restart: always
    # 环境变量 TZ 设置时区为东八区
    # JAVA_OPTS 设置Java程序启动所需内存大小(可能无效果)
    environment:
      PUID: 1000 # 自己改这两个
      PGID: 1000 #
      TZ: Asia/Shanghai
      JAVA_OPTS: "-Xms64m -Xmx128m"
      # 如果你了解Java的运行逻辑    java ${JAVA_OPTS} -jar danmuji.jar ${JAVA_OPTS2}
      JAVA_OPTS2: "" 
    # “:”前面是本机地址可自由更改，“:”后面为容器内固定路径
    # web服务端口
    ports:
      - 23333:23333
    # 映射文件夹(非必须)
    volumes:
      - /danmuji/Danmuji_log:/danmuji/Danmuji_log
      - /danmuji/guardFile:/danmuji/guardFile
      - /danmuji/log:/danmuji/log
    # 日志 日志大小1m 日志数量2个
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "2"
