# 利用GitHub Action自动构建多框架的docker镜像
name: Buildx_Danmuji_Docker_Source_Code

on:
  # master分支的push操作会触发当前脚本的执行
  push:
    branches: [ master ]
  # master分支的pr操作会触发当前脚本的执行
#  pull_request:
#    branches: [ master ]
  # 定时任务,分时日月年,为国际标准时间16点,对应中国时间0点
#  schedule:
#    - cron: '0 16 * * *'
  # 点击star时开始任务
#  watch:
#    types: started


jobs:
  Buildx_Danmuji_Docker_Source_Code:
    # 运行在Ubuntu系统上
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'test')"
    # 步骤
    steps:
      - name: Prepare
        id: prepare
        # IMAGE_NAME ： 镜像名称
        # VERSION ： 源码版本
        # DOCKERHUB_VERSION ： DockerHub 镜像版本
        # TAG_VERSION ： 标签版本
        # TAG_LATEST ： 最新版本
        run: |
          IMAGE_NAME=danmuji-code
          VERSION=$(curl -sX GET "https://api.github.com/repos/BanqiJane/Bilibili_Danmuji/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')
          DOCKERHUB_VERSION=$(curl -sX GET "https://hub.docker.com/v2/repositories/zzcabc/danmuji-code/tags" | awk '{print $644;exit}' FS='[""]')
          TAG_VERSION="${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${VERSION}"
          TAG_LATEST="${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:latest"
          echo ::set-output name=image_name::${IMAGE_NAME}
          echo ::set-output name=build_args::${VERSION}
          echo ::set-output name=dockerhub_version::${DOCKERHUB_VERSION}
          echo ::set-output name=tag_version::${TAG_VERSION}
          echo ::set-output name=tag_latest::${TAG_LATEST}
      # 切换到主分支
      - name: Checkout
        if: "contains(github.event.head_commit.message, 'test')"
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        uses: actions/checkout@main

      - name: Set up QEMU
        if: "contains(github.event.head_commit.message, 'test')" 
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        uses: docker/setup-qemu-action@v1

        # 初始化Docker Buildx
      - name: Set up Docker Buildx
        if: "contains(github.event.head_commit.message, 'test')"
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        uses: docker/setup-buildx-action@v1

        # 登录到DockerHub
      - name: Login to DockerHub
        if: "contains(github.event.head_commit.message, 'test')"
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # 初始化 JDK8 环境
      - name: Set up JDK 8
        if: "contains(github.event.head_commit.message, 'test')"
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      # Docker_Buildx_Danmuji/Docker_Buildx_Danmuji/Bilibili_Danmuji/build/libs/xxxxxxxxxxx
      # 使用Gradle编译构建同时命名danmuji.jar
      - name: Build with Gradle
        if: "contains(github.event.head_commit.message, 'test')"
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        run: |
          sudo apt-get install git
          git clone https://github.com/BanqiJane/Bilibili_Danmuji.git
          cd Bilibili_Danmuji
          sudo chmod +x ./gradlew
          sudo ./gradlew build -x test
          sudo mv $(find build -type f -size +10M) ././danmuji.jar
      # 构建 Armv5 框架镜像
      - name: Build linux/arm/v5
        if: "contains(github.event.head_commit.message, 'test')"
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.code
          platforms: linux/arm/v5
          push: true
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tag_version }}-armv5,${{ steps.prepare.outputs.tag_latest }}-armv5
      # 构建 Armv7 框架镜像
      - name: Build linux/arm/v7
        if: "contains(github.event.head_commit.message, 'test')"
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.code
          platforms: linux/arm/v7
          push: true
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tag_version }}-arm32v7,${{ steps.prepare.outputs.tag_latest }}-arm32v7
      # 构建 Arm64 框架镜像
      - name: Build linux/arm64
        if: "contains(github.event.head_commit.message, 'test')"
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.code
          platforms: linux/arm64
          push: true
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tag_version }}-arm64v8,${{ steps.prepare.outputs.tag_latest }}-arm64v8
      # 构建 386 框架镜像
      - name: Build linux/386
        if: "contains(github.event.head_commit.message, 'test')"
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.code
          platforms: linux/386
          push: true
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tag_version }}-386,${{ steps.prepare.outputs.tag_latest }}-386
      # 构建 Amd64 框架镜像
      - name: Build linux/amd64
        if: "contains(github.event.head_commit.message, 'test')"
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.code
          platforms: linux/amd64
          push: true
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tag_version }}-amd64,${{ steps.prepare.outputs.tag_latest }}-amd64
      # 构建 ppc64le 框架镜像
      - name: Build linux/ppc64le
        if: "contains(github.event.head_commit.message, 'test')"
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.code
          platforms: linux/ppc64le
          push: true
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tag_version }}-ppc64le,${{ steps.prepare.outputs.tag_latest }}-ppc64le
      # 构建 s390x 框架镜像
      - name: Build linux/s390x
        if: "contains(github.event.head_commit.message, 'test')"
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.code
          platforms: linux/s390x
          push: true
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tag_version }}-s390x,${{ steps.prepare.outputs.tag_latest }}-s390x
      # 构建 Windows 框架镜像
      # - name: Build windows/amd64
      #   if: "contains(github.event.head_commit.message, 'test')"
      #   #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile.windows
      #     platforms: windows/amd64
      #     push: true
      #     build-args: ${{ steps.prepare.outputs.build_args }}
      #     tags: ${{ steps.prepare.outputs.tag_version }}-windows,${{ steps.prepare.outputs.tag_latest }}-windows
      #创建并推送多架构镜像
      - name: Create and push manifest lists
        if: "contains(github.event.head_commit.message, 'test')"
        #if: ${{ steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.build_args }}
        run: |
          docker manifest create -a ${{ steps.prepare.outputs.tag_version }} \
              ${{ steps.prepare.outputs.tag_version }}-386       \
              ${{ steps.prepare.outputs.tag_version }}-amd64     \
              ${{ steps.prepare.outputs.tag_version }}-ppc64le   \
              ${{ steps.prepare.outputs.tag_version }}-s390x     \
              ${{ steps.prepare.outputs.tag_version }}-armv5     \
              ${{ steps.prepare.outputs.tag_version }}-arm32v7   \
              ${{ steps.prepare.outputs.tag_version }}-arm64v8
              
          docker manifest annotate ${{ steps.prepare.outputs.tag_version }} \
              ${{ steps.prepare.outputs.tag_version }}-386 \
              --arch=386 \
              --os=linux  \
              --os-version=openjdk:8u181-jre-slim

          docker manifest annotate ${{ steps.prepare.outputs.tag_version }} \
              ${{ steps.prepare.outputs.tag_version }}-amd64 \
              --arch=amd64 \
              --os=linux  \
              --os-version=openjdk:8u181-jre-slim

          docker manifest annotate ${{ steps.prepare.outputs.tag_version }} \
              ${{ steps.prepare.outputs.tag_version }}-ppc64le \
              --arch=ppc64le \
              --os=linux  \
              --os-version=openjdk:8u181-jre-slim

          docker manifest annotate ${{ steps.prepare.outputs.tag_version }} \
              ${{ steps.prepare.outputs.tag_version }}-s390x \
              --arch=s390x \
              --os=linux  \
              --os-version=openjdk:8u181-jre-slim

          docker manifest annotate ${{ steps.prepare.outputs.tag_version }} \
              ${{ steps.prepare.outputs.tag_version }}-armv5 \
              --arch=arm \
              --os=linux  \
              --variant=v5 \
              --os-version=openjdk:8u181-jre-slim

          docker manifest annotate ${{ steps.prepare.outputs.tag_version }} \
              ${{ steps.prepare.outputs.tag_version }}-arm32v7 \
              --arch=arm \
              --os=linux  \
              --variant=v7 \
              --os-version=topenjdk:8u181-jre-slim

          docker manifest annotate ${{ steps.prepare.outputs.tag_version }} \
              ${{ steps.prepare.outputs.tag_version }}-arm64v8 \
              --arch=arm64 \
              --os=linux  \
              --variant=v8 \
              --os-version=openjdk:8u181-jre-slim
              

          
          docker manifest push ${{ steps.prepare.outputs.tag_version }}



          docker manifest create -a ${{ steps.prepare.outputs.tag_latest }} \
              ${{ steps.prepare.outputs.tag_latest }}-386       \
              ${{ steps.prepare.outputs.tag_latest }}-amd64     \
              ${{ steps.prepare.outputs.tag_latest }}-ppc64le   \
              ${{ steps.prepare.outputs.tag_latest }}-s390x     \
              ${{ steps.prepare.outputs.tag_latest }}-armv5     \
              ${{ steps.prepare.outputs.tag_latest }}-arm32v7   \
              ${{ steps.prepare.outputs.tag_latest }}-arm64v8

          docker manifest annotate ${{ steps.prepare.outputs.tag_latest }} \
              ${{ steps.prepare.outputs.tag_latest }}-386 \
              --arch=386 \
              --os=linux  \
              --os-version=openjdk:8u181-jre-slim

          docker manifest annotate ${{ steps.prepare.outputs.tag_latest }} \
              ${{ steps.prepare.outputs.tag_latest }}-amd64 \
              --arch=amd64 \
              --os=linux  \
              --os-version=openjdk:8u181-jre-slim

          docker manifest annotate ${{ steps.prepare.outputs.tag_latest }} \
              ${{ steps.prepare.outputs.tag_latest }}-ppc64le \
              --arch=ppc64le \
              --os=linux  \
              --os-version=openjdk:8u181-jre-slim

          docker manifest annotate ${{ steps.prepare.outputs.tag_latest }} \
              ${{ steps.prepare.outputs.tag_latest }}-s390x \
              --arch=s390x \
              --os=linux  \
              --os-version=openjdk:8u181-jre-slim

          docker manifest annotate ${{ steps.prepare.outputs.tag_latest }} \
              ${{ steps.prepare.outputs.tag_latest }}-armv5 \
              --arch=arm \
              --os=linux  \
              --variant=v5 \
              --os-version=openjdk:8u181-jre-slim

          docker manifest annotate ${{ steps.prepare.outputs.tag_latest }} \
              ${{ steps.prepare.outputs.tag_latest }}-arm32v7 \
              --arch=arm \
              --os=linux  \
              --variant=v7 \
              --os-version=openjdk:8u181-jre-slim

          docker manifest annotate ${{ steps.prepare.outputs.tag_latest }} \
              ${{ steps.prepare.outputs.tag_latest }}-arm64v8 \
              --arch=arm64 \
              --os=linux  \
              --variant=v8 \
              --os-version=openjdk:8u181-jre-slim
          


          docker manifest push ${{ steps.prepare.outputs.tag_latest }}


