# 利用GitHub Action自动构建多框架的docker镜像
name: Build

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Forced' 
        required: true
        default: 'true'
  # main分支的push操作会触发当前脚本的执行
#  push:
#    branches: [ main ]
  # main分支的pr操作会触发当前脚本的执行
#  pull_request:
#    branches: [ main ]
  # 定时任务,分时日月年,为国际标准时间16点,对应中国时间0点
  schedule:
    - cron: '0 16 * * *'
  # 点击star时开始任务
  watch:
    types: started


jobs:
  Build:
    # 运行在Ubuntu系统上
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 切换到主分支
      - name: Checkout
        uses: actions/checkout@main

      - name: Prepare
        id: prepare
        # IMAGE_NAME ： 镜像名称
        # ALI_ADD ：阿里镜像地址
        # GITHUB_VERSION ： 源码版本
        # DOCKERHUB_VERSION ： DockerHub 镜像版本
        # TAG_VERSION ： 标签版本 zzcabc/danmuji:2.4.9
        # TAG_LATEST ： 最新版本 zzcabc/pixivbiu-test:latest
        # ALI_VERSION ： registry.cn-hangzhou.aliyuncs.com/zzcabc/danmuji:2.4.9
        # ALI_LATEST : registry.cn-hangzhou.aliyuncs.com/zzcabc/danmuji:latest
        # AUTO_UPDATE_TAG : zzcabc/danmuji:autoupdate
        # AUTO_UPDATE_ALI : registry.cn-hangzhou.aliyuncs.com/zzcabc/danmuji:autoupdate
        run: |
          GITHUB_VERSION=$(curl -sX GET "https://api.github.com/repos/BanqiJane/Bilibili_Danmuji/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')
          DOCKERHUB_VERSION=$(cat currentVersion)
          echo "github_version=$GITHUB_VERSION" >> $GITHUB_OUTPUT
          echo "dockerhub_version=$DOCKERHUB_VERSION" >> $GITHUB_OUTPUT

          IMAGE_NAME=danmuji
          DOCKERHUB_NAME_SPACE="${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}"
          
          TAG_VERSION="$DOCKERHUB_NAME_SPACE:${GITHUB_VERSION}"
          TAG_LATEST="$DOCKERHUB_NAME_SPACE:latest"
          AUTO_UPDATE_TAG="$DOCKERHUB_NAME_SPACE:autoupdate"
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT
          echo "TAG_LATEST=$TAG_LATEST" >> $GITHUB_OUTPUT
          echo "AUTO_UPDATE_TAG=$AUTO_UPDATE_TAG" >> $GITHUB_OUTPUT


          echo "DockerHub: $TAG_VERSION $TAG_LATEST $AUTO_UPDATE_TAG"
          

          GHCR_ADD=ghcr.io
          GHCR_NAME_SPACE="${{ github.repository_owner }}/$IMAGE_NAME"
          GHCR_VERSION="${GHCR_ADD}/$GHCR_NAME_SPACE:${GITHUB_VERSION}"
          GHCR_LATEST="${GHCR_ADD}/$GHCR_NAME_SPACE:latest"
          GHCR_AUTO_UPDATE="${GHCR_ADD}/$GHCR_NAME_SPACE:autoupdate"
          echo "GHCR_VERSION=$GHCR_VERSION" >> $GITHUB_OUTPUT
          echo "GHCR_LATEST=$GHCR_LATEST" >> $GITHUB_OUTPUT
          echo "GHCR_AUTO_UPDATE=$GHCR_AUTO_UPDATE" >> $GITHUB_OUTPUT

          echo "GHCR: $GHCR_VERSION $GHCR_LATEST $GHCR_AUTO_UPDATE"

          ALI_ADD=registry.cn-hangzhou.aliyuncs.com
          ALI_VERSION="${ALI_ADD}/${{ secrets.ALIYUN_NAMESPACES }}/${IMAGE_NAME}:${GITHUB_VERSION}"
          ALI_LATEST="${ALI_ADD}/${{ secrets.ALIYUN_NAMESPACES }}/${IMAGE_NAME}:latest"
          AUTO_UPDATE_ALI="${ALI_ADD}/${{ secrets.ALIYUN_NAMESPACES }}/${IMAGE_NAME}:autoupdate"
          echo "ALI_VERSION=$ALI_VERSION" >> $GITHUB_OUTPUT
          echo "ALI_LATEST=$ALI_LATEST" >> $GITHUB_OUTPUT

          echo "github $GITHUB_VERSION dockerhub  $DOCKERHUB_VERSION"

      - name: Set up QEMU
        if: ${{ github.event.inputs.Forced == 'true' || steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.github_version }}
        uses: docker/setup-qemu-action@v3

      # 初始化Docker Buildx
      - name: Set up Docker Buildx
        if: ${{ github.event.inputs.Forced == 'true' || steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.github_version }}
        uses: docker/setup-buildx-action@v3

      # 登录到DockerHub
      - name: Login to DockerHub
        if: ${{ github.event.inputs.Forced == 'true' || steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.github_version }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # 登录到GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      # 登录到阿里镜像仓库
      # - name: Login To Alibaba Cloud Container Registry
      #   if: ${{ github.event.inputs.Forced == 'true'|| steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.github_version }}
      #   run: |
      #     docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PWD }} registry.cn-hangzhou.aliyuncs.com

      # 初始化 JDK8 环境
      - name: Set up JDK 8
        if: ${{ github.event.inputs.Forced == 'true' || steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.github_version }}
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      # 使用Gradle编译构建同时命名danmuji.jar
      - name: Build with Gradle
        if: ${{ github.event.inputs.Forced == 'true' || steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.github_version }}
        run: |
          sudo apt-get install -y git
          git clone https://github.com/BanqiJane/Bilibili_Danmuji.git
          cd Bilibili_Danmuji
          sudo chmod +x ./gradlew
          sudo ./gradlew build -x test
          sudo mv $(find build -type f -size +10M) ./danmuji.jar

      # 自动更新的推送
      - name: Build and Push Auto Update
        if: ${{ github.event.inputs.Forced == 'true' || steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.github_version }}
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8
          file: ./Dockerfile.Update
          context: .
          push: true
          tags: |
            ${{ steps.prepare.outputs.AUTO_UPDATE_TAG }}
            ${{ steps.prepare.outputs.GHCR_AUTO_UPDATE }}

      # 构建Amd64和Arm64的镜像
      - name: Build and Push Amd64 and Arm64
        if: ${{ github.event.inputs.Forced == 'true' || steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.github_version }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64/v8
          file: ./Dockerfile
          context: .
          push: true
          tags: |
            ${{ steps.prepare.outputs.TAG_VERSION }}
            ${{ steps.prepare.outputs.TAG_LATEST }}
            # ${{ steps.prepare.outputs.GHCR_VERSION }}
            # ${{ steps.prepare.outputs.GHCR_LATEST }}]
    
      # 初始化版本号与git 
      - name: commit
        if: ${{ github.event.inputs.Forced == 'true' || steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.github_version }}
        run: |
          echo "${{ steps.prepare.outputs.github_version }}" > currentVersion
          git config --global user.name zhaocheng
          git config --global user.email zhaocheng990105@gmail.com
          git add currentVersion
          sed -i 's/${{ steps.prepare.outputs.dockerhub_version }}/${{ steps.prepare.outputs.github_version }}/g' README.md
          git commit -m "当前版本是:${{ steps.prepare.outputs.github_version }}" -a
      
      # 推送版本号到GitHub 
      - name: Push changes
        if: ${{ github.event.inputs.Forced == 'true' || steps.prepare.outputs.dockerhub_version != steps.prepare.outputs.github_version }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
